on:
  pull_request:
    branches:
      - master

name: pull-request
jobs:
  pytest:
    strategy:
      matrix:
        pyv: [ 3.7, 3.8 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0
      - name: install dep
        run: |
          sudo apt-get install gcc libpq-dev -y
          sudo apt-get install python-dev  python-pip -y
          sudo apt-get install python${{ matrix.python-version }}-dev python${{ matrix.python-version }}-pip python${{ matrix.python-version }}-venv python${{ matrix.python-version }}-wheel -y
          sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
          pip install numpy
          pip install wheel
          pip install -r requirements.txt
      - name: make-cdsapirc
        run: |
          echo {{ secrets.cdsapirc }} > ~/.cdsapirc
      - name: run
        run: |
          pytest -s -v
