on:
  push:
    branches:
      - master

name: master
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'VERSION-SKIP-CI')"
    strategy:
      matrix:
        pyv: [ 3.7, 3.8 ]
    steps:

      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v2
        with:
          pyv: ${{ matrix.pyv }}

      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: build
        run: |
          sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
          pip install numpy
          pip install -r requirements.txt
          python iterate_version.py
          echo "Version is $(more VERSION.txt)"

      - name: commit version
        run: |
          git add VERSION.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "VERSION-SKIP-CI"

      - name: Push version
        if: ${{ matrix.pyv == 3.8 }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_CICD }}
          branch: master
          force: true

      - name: make doc
        run: |
          pip install pdoc3
          pdoc --html climat -o docs
          mv docs/climat/* docs/
          rm -r docs/climat

      - name: commit doc
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs"

      - name: Push doc
        if: ${{ matrix.pyv == 3.8 }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_CICD }}
          branch: "gh-pages"
          force: true

#      - name: topypi
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          user: ${{ secrets.pypi_login }}
#          password: ${{ secrets.pypi_passwd }}
#          skip_existing: true
#          verbose: true

#      - name: todocker
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.docker_login }}
#          password: ${{ secrets.docker_passwd }}
#          repository: advestisrepositories/${{ env.REPO_NAME }}
#          tag_with_ref: true